version: "3"

services:
  monitoring-database:
    image: postgres
    container_name: monitoring-database
    restart: always
    environment:
      POSTGRES_USER: monitoring
      POSTGRES_PASSWORD: Monitoring_database_password1
      POSTGRES_DB: monitoring_db

  monitoring:
    image: cfei/monitoring-service
    container_name: monitoring
    ports:
      - 5002:80
    environment:
      MONITORING_POSTGRES_CONNECTION_STRING: "Host=monitoring-database;Port=5432;Database=monitoring_db;Username=monitoring;Password=Monitoring_database_password1"
    depends_on:
      - monitoring-database
